name: nearby_point
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  flutter_polyline_points: ^2.0.1

  provider: ^6.1.1

  # Utils
  json_annotation: ^4.8.1
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/poi.json
